import assert from 'node:assert/strict';
import test from 'node:test';

import {
    calculateCashClosureInternalRatio,
    getDocumentLinkedPayrollMealTotal,
    isCashClosureRcAllowed,
} from './cashClosureAdjustments.js';

test('alimentacion planilla affects RC exactly like descuento de la casa', () => {
    const withHouseDiscount = calculateCashClosureInternalRatio({
        cardTotal: 100,
        transferTotal: 200,
        houseDiscountTotal: 50,
        cashIncomeNetTotal: 500,
    });
    const withPayrollMeal = calculateCashClosureInternalRatio({
        cardTotal: 100,
        transferTotal: 200,
        payrollMealTotal: 50,
        cashIncomeNetTotal: 500,
    });

    assert.deepEqual(withPayrollMeal, withHouseDiscount);
    assert.deepEqual(withPayrollMeal, {
        nonCashTotal: 350,
        rc: -150,
        cashResidual: 150,
    });
});

test('combines both non-cash adjustments without changing their signs', () => {
    assert.deepEqual(calculateCashClosureInternalRatio({
        cardTotal: 120,
        transferTotal: 80,
        houseDiscountTotal: 15,
        payrollMealTotal: 25,
        cashIncomeNetTotal: 240,
    }), {
        nonCashTotal: 240,
        rc: 0,
        cashResidual: 0,
    });
});

test('allows the cash residual and up to ten cordobas over stamped documents', () => {
    assert.equal(isCashClosureRcAllowed(-29504.50), true);
    assert.equal(isCashClosureRcAllowed(0), true);
    assert.equal(isCashClosureRcAllowed(10), true);
    assert.equal(isCashClosureRcAllowed(10.01), false);
});

test('only document-linked payroll meals participate in the stamped-document RC', () => {
    assert.equal(getDocumentLinkedPayrollMealTotal([
        { description: 'Vale interno', amount: 14732.47 },
        { description: 'F-8001', amount: 250, autoGenerated: true, sourceType: 'invoice' },
        { description: 'R-0100', amount: 125, sourceDocumentId: 'receipt-0100' },
    ]), 375);
});
