const money = (value = 0) => {
    const parsed = Number(value || 0);
    return Number.isFinite(parsed) ? Math.round(parsed * 100) / 100 : 0;
};

export const CASH_CLOSURE_RC_TOLERANCE = 10;

export const isCashClosureRcWithinTolerance = (
    value = 0,
    tolerance = CASH_CLOSURE_RC_TOLERANCE
) => Math.abs(money(value)) <= Math.abs(money(tolerance));

export const getDocumentLinkedPayrollMealTotal = (rows = []) => money(
    (Array.isArray(rows) ? rows : []).reduce((total, row = {}) => {
        const sourceType = String(row.sourceType || '').trim().toLowerCase();
        const isDocumentLinked = row.autoGenerated === true
            || Boolean(row.autoSourceKey)
            || Boolean(row.sourceDocumentId)
            || sourceType === 'invoice'
            || sourceType === 'receipt';
        if (!isDocumentLinked) return total;
        return total + money(row.amount ?? row.total ?? row.value);
    }, 0)
);

export const calculateCashClosureInternalRatio = ({
    cardTotal = 0,
    transferTotal = 0,
    houseDiscountTotal = 0,
    payrollMealTotal = 0,
    cashTotal = 0,
    cashIncomeNetTotal = 0,
} = {}) => {
    const nonCashTotal = money(money(cardTotal)
        + money(transferTotal)
        + money(houseDiscountTotal)
        + money(payrollMealTotal));
    const enteredCashTotal = money(cashTotal);
    const incomeTotal = money(cashIncomeNetTotal);
    const reconciledPaymentTotal = money(nonCashTotal + enteredCashTotal);

    return {
        nonCashTotal,
        enteredCashTotal,
        reconciledPaymentTotal,
        rc: money(reconciledPaymentTotal - incomeTotal),
        cashResidual: money(incomeTotal - nonCashTotal),
    };
};
